version: "3.9"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID  # defaults to None
      API_HASH: $API_HASH  # defaults to None
      BOT_TOKEN: $BOT_TOKEN 
      LOG_CHANNEL: $LOG_CHANNEL
      AUTH_USERS: $AUTH_USERS
      CHNAME: $CHNAME
